### PR TITLE
feat(dapp): remove seller license verification

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by richard-ramos** [comment]
Ah right! I did not have the problem with the wallet because I was using `master` and it doesnt have the EIP1102 change. Good catch!

**Comment by jrainville** [comment]
Oh, my PR is not merged yet, makes sense. Should I merge it then you update, or you merge yours then I update?
I already have to change where I call the enable on the offerList, so it's not a problem for me

**Comment by jrainville** [comment]
I'll let you merge yours first. I'll keep working on my old branch before merging it

**Comment by richard-ramos** [comment]
I made some quick changes to remove some calls related to the license feature. However I think I'll not remove functionality from the license feature in case we decide to use Licenses for something.

**Pull request merged**
