### PR TITLE
Change MetadataStore#addOrUpdateUser

### PR DESCRIPTION
**Pull request by arsenyjin**
Added signature to addOrUpdateUser as mentioned in https://github.com/status-im/status-teller-network/issues/206

### CODE REVIEW

**Comment by 3esmit** [comment]
This solves the problem of the issue, so the metadata is not wide open anymore. However we should rethink about the reuse of signatures. Perhaps we can consider adding TTL, nonce (or orderid, if we keep Escrow and Metadata related).

**Comment by iurimatias** [comment]
the tests currently fail

**Comment by arsenyjin** [comment]
I probably have to modify tests then, as I've changed the way several functions work

**Comment by arsenyjin** [comment]
Closed the PR as signature mechanics probably need more modifications

**Pull request closed without merging**
